### ISSUE TITLE
(Suggestion) New config for the park gear mode

### ISSUE THREAD

**Issue by ZigzagAwaka** [1A3Dev/LC-BetterVehicleControls#1]
The truck is supposed to explode when the player is trying to move while it's parked
It could be nice to keep the Automatic Gearbox option but adding a config to not switch the gear when it's parked

For example, it's at park, you try to move, it doesn't change and explosion!
You have to change manually park for drive & reverse to don't explode
When it's at drive or reverse, the Automatic Gearbox option works as intended

That's all ! Very great mod btw

**Comment by 1A3Dev** [comment]
That already exists :) I did a separate option for the auto park to keep that.

**Comment by 1A3Dev** [comment]
> The truck is supposed to explode when the player is trying to move while it's parked

I am aware of that but my initial thoughts were that it didn't make sense for it to not automatically switch from parked.

However now I'm thinking about it, the parked gear would kinda be like a handbrake so I'll add a config option for that in the next few hours

**Comment by 1A3Dev** [comment]
Added in v1.0.2

**Comment by ZigzagAwaka** [comment]
Wow thanks
