### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by mrakrmakmrka** [1A3Dev/LC-BetterVehicleControls#10]
To be more precise, it is an old feature, but with a different addition, namely, the ability to switch the magnet by pressing a key on the keyboard, but regardless of the distance, between the machine and the magnet. So that you don't have to wait about 5 seconds while holding the magnet lever in the car.

**Comment by 1A3Dev** [comment]
> To be more precise, it is an old feature, but with a different addition, namely, the ability to switch the magnet by pressing a key on the keyboard

Like you said that's already a thing

> regardless of the distance, between the machine and the magnet

The distance limit was to balance it out as you have to either toggle it as you are leaving the ship or toggle it when you get back to the ship which means you have to think carefully and can't just toggle it from far away if enemies are around the ship

> So that you don't have to wait about 5 seconds while holding the magnet lever in the car

This mod doesn't add a magnet lever in the car, that's a different mod. This mod has a keybind to toggle the magnet which toggles it instantly
