### ISSUE TITLE
problems with mod

### ISSUE THREAD

**Issue by dustojnicek** [1A3Dev/LC-BetterVehicleControls#2]
hi i have a little problem with my mod because it doesn't work.

**Comment by 1A3Dev** [comment]
That's a bit vague? What specific issues are you having with this mod?

**Comment by dustojnicek** [comment]
the steering is still the same
but the shifter works

**Comment by dustojnicek** [comment]
the steering is still manual

**Comment by 1A3Dev** [comment]
Have you enabled it in the config?

**Comment by dustojnicek** [comment]
where do i find the config

**Comment by dustojnicek** [comment]
ohh

**Comment by dustojnicek** [comment]
i found it, thank you so much. :)

**Comment by dustojnicek** [comment]
i open it with notepad right?

**Comment by 1A3Dev** [comment]
Any text editor would work

**Comment by dustojnicek** [comment]
oki
