### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by ZigzagAwaka** [1A3Dev/LC-BetterVehicleControls#4]
With your last update, i don't see the rebindable controls in Input utils controls parameters
Also, when boosting with spacebar the truck just explodes lmao (only when you are moving), that's funny but not supposed to happen i think

**Comment by ZigzagAwaka** [comment]
Ah sorry, didn't update the mod to 1.0.7
And for the second issue, i can't replicate it using 1.0.7 so it was fixed?

**Comment by ZigzagAwaka** [comment]
wait no, it's still present

**Comment by 1A3Dev** [comment]
The second would've been since ofc in v1.0.6 spacebar was also brake, so you would've been braking and moving at the same time which ofc explodes you

**Comment by 1A3Dev** [comment]
> wait no, it's still present

Are you sure? I'm trying it and I can't seem to reproduce it

**Comment by ZigzagAwaka** [comment]
Well it's a little more difficult to do than in the previous version
You have to press spacebar and hold it while moving forward at a medium/great speed

**Comment by ZigzagAwaka** [comment]
Oh maybe it's vanilla ?

**Comment by 1A3Dev** [comment]
This mod doesn't add any additional explosion logic so any explosion that happens would be vanilla

**Comment by ZigzagAwaka** [comment]
I just tried without the mod and yes it's vanilla lmao
Anyway, thanks for the 1.0.7 update
