### ISSUE TITLE
[FEATUREY REQUESTSS] Adda configs ta changey camera heights whiley onna seats!

### ISSUE THREAD

**Issue by Flloppis** [1A3Dev/LC-BetterVehicleControls#5]
Becausey summa times itta really hards ta see wherey ams drivin'!!
Amma talls enoughs ta see tha windows properlyy!! >;c

![image](https://github.com/1A3Dev/LC-BetterVehicleControls/assets/157853816/b56d9278-efcd-4f68-b92f-a2477d37741f)
Fromma this ^

Ta something likey thissaa!!! v
![image](https://github.com/1A3Dev/LC-BetterVehicleControls/assets/157853816/a837a58a-3b47-41cb-80af-d5c087d0036a)

**Comment by 1A3Dev** [comment]
The increased height is already part of another mod called [CruiserImproved](https://thunderstore.io/c/lethal-company/p/DiggC/CruiserImproved/) which does some different improvements to the cruiser. There shouldn't be any compatibility issues when using that mod alongside this one.

**Comment by Flloppis** [comment]
O oki!!!! Thanksii yer!!!
