### ISSUE TITLE
Possible additions

### ISSUE THREAD

**Issue by Fellow9000** [1A3Dev/LC-BetterVehicleControls#7]
Would it be possible to add a third person camera that hovers over the cruiser, or a visible health and boost indicator located on the dashboard?

**Comment by 1A3Dev** [comment]
That seems more like something that would be better to suggest for CruiserImproved https://github.com/digger1213/CruiserImproved/ (which I'd highly suggest using alongside this mod)

**Comment by Fellow9000** [comment]
Ok, thank you.
