### ISSUE TITLE
Disabling features does not revert to normal behaviour

### ISSUE THREAD

**Issue by RaphaelArctic** [1A3Dev/LC-BetterVehicleControls#8]
If the settings automatic gearbox, handbrake release and handbrake pull are disabled (leaving only center wheel left enabled), the manual handbrake ("S") does not work as expected. In Drive and Reverse, pressing S still reverses the car. Thus, there is no handbrake anymore as both automatic and manual do not work.

This is quite the issue as this is seemingly the only mod that has the automatic center wheel function, which people would want exclusively, while still driving a manual.
Hope this can get fixed <3

**Comment by 1A3Dev** [comment]
This isn't a bug, you need to change the keybinds to be the same as vanilla as shown on the README https://github.com/1A3Dev/LC-BetterVehicleControls?tab=readme-ov-file#vanilla-controls
